name = "beacon-cm"
main = "_worker.js"
compatibility_date = "2025-11-04"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[[routes]]
pattern = "beacon-pages-github-io.karsontsang23.workers.dev/*"
zone_name = "beacon-pages-github-io.karsontsang23.workers.dev"

# ...
[[d1_databases]]
binding = "DB"
database_name = "beacon-tunnel-db"
database_id = "57ad8dc0-c99a-4259-8c98-995f9a305917"

[[kv_namespaces]]
binding = "KV"
id = "0d3308096e1147fb87078715c4ca4af5"
# ...

[triggers]
crons = ["0 */6 * * *"]
